name: glowberry-github-actions-docker-compose-pulumi-koyeb

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      
      - name: Pulumi Deploy
        run: |
          export KOYEB_TOKEN=${{secrets.KOYEB_TOKEN}}
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$HOME/.pulumi/bin:$PATH
          pulumi preview
          pulumi up -y