name: glowberry-github-actions-docker-compose-pulumi-koyeb

on:
  push:
    branches:
      - main

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4