name: glowberry-github-actions-docker-compose-pulumi-koyeb

on:
  push:
    branches:
      - main

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      
      - name: Koyeb Setup and Deploy
        working-directory: ./pulumi-koyeb
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          export KOYEB_TOKEN=${{secrets.KOYEB_TOKEN}}
          export PULUMI_ACCESS_TOKEN=${{secrets.PULUMI_ACCESS_TOKEN}}
          curl -fsSL https://get.pulumi.com | sh
          mkdir -p ~/.pulumi/plugins/resource-koyeb-v0.1.11
          curl -L https://github.com/koyeb/pulumi-koyeb/releases/download/v0.1.11/pulumi-resource-koyeb-v0.1.11-linux-amd64.tar.gz | tar -xz -C ~/.pulumi/plugins/resource-koyeb-v0.1.11
          export PATH=$HOME/.pulumi/bin:$PATH
          pulumi login
          pulumi stack select pulumi-koyeb
          pulumi preview
          pulumi up -y


